name: PR Branch Labeler

on: pull_request

ðŸš€ rebase merge:
  head: "main"

ðŸš€ squash merge:
  head: "*/dev/*"

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        if: github.event.action == 'opened' # Only run the action when the PR was first opened
        uses: ffittschen/pr-branch-labeler@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
