name: Type labeler

on:
  pull_request:
  issues:

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: add âœ¨ feature label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issues.title, '[feat]') || startsWith(github.event.pull_request.title, '[feat]') }}
        with:
          labels: âœ¨ feature

      - name: add ğŸ› bug-fix label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issues.title, '[fix]') || startsWith(github.event.pull_request.title, '[fix]') }}
        with:
          labels: ğŸ› bug-fix

      - name: add â™»ï¸ refactor label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issues.title, '[refactor]') || startsWith(github.event.pull_request.title, '[refactor]') }}
        with:
          labels: â™»ï¸ refactor
          
      - name: add ğŸ¨ style label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issues.title, '[style]') || startsWith(github.event.pull_request.title, '[style]') }}
        with:
          labels: ğŸ¨ style

      - name: add ğŸ» chore label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issues.title, '[chore]') || startsWith(github.event.pull_request.title, '[chore]') }}
        with:
          labels: ğŸ» chore

      - name: add âœ… test label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issues.title, '[test]') || startsWith(github.event.pull_request.title, '[test]') }}
        with:
          labels: âœ… test

      - name: add ğŸ“ docs label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issues.title, '[docs]') || startsWith(github.event.pull_request.title, '[docs]') }}
        with:
          labels: ğŸ“ docs
          
